# Generated by Django 5.2.6 on 2025-09-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_from_ac_43b72c_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_to_acco_f0a449_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_status_c5427f_idx',
        ),
    ]
