# Generated by Django 4.2.7 on 2025-09-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('debit', 'Debit Card'), ('credit', 'Credit Card')], max_length=10)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('pending', 'Pending Activation')], default='pending', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('international_usage', models.BooleanField(default=False)),
                ('online_usage', models.BooleanField(default=True)),
                ('contactless_enabled', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_cycle_day', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_cards', to='accounts.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_name', models.CharField(max_length=200)),
                ('merchant_category', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('authorization_code', models.CharField(max_length=20)),
                ('is_international', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.card')),
            ],
            options={
                'db_table': 'card_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
